PATCH http://localhost:3000/posts
Content-Type : application/json
{
 "id":10,  
 "title" : "Whats new with typescript",
 "postType" : "post",
 "slug" : "new-with-nestj-14",
 "status" : "draft",
 "content" : "test content 1",
 "tags" : [3,4]
} 