POST http://localhost:3000/users
Content-Type : application/json
{
    "firstName" : "Hamed",
    "lastName" : "Zibi",
    "email" : "hamedzibi@gmail.com",
    "password" : "!Hamed102030"
}





POST http://localhost:3000/users/create-many
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiaGFtZWR6aWJpQGdtYWlsLmNvbSIsImlhdCI6MTc3NjIzMzc2NywiZXhwIjoxNzc2MjM3MzY3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.FkG8VlCVxtR8FPmU7gtkIoqhN4LiErvwhtlij2Ba3Q8
{
  "users": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "email": "john@example.com",
      "password": "SecurePass123!"
    },
    {
      "firstName": "Jane",
      "lastName": "Smith",
      "email": "jane@example.com",
      "password": "SecurePass456!"
    }
  ]
}